### ISSUE TITLE
Velero Restore not working as described in Doc

### ISSUE THREAD

**Issue by JustinGuese** [canonical/microk8s.io#555]
## Summary

https://microk8s.io/docs/velero

I followed the steps multiple times on clean AWS Ubuntu 22 instances, and even though a Postgresql deployment had been tagged with 

```
  annotations:
    backup.velero.io/backup-volumes: psql-pv,psql-pvc
```

and the hostpath patch applied to velero, it restores the deployments, but not the PVC, even though I see the "restic" folder in the S3 bucket.

## Process

1. Machine that is going to be backed up

`velero backup create fullbackup`

2. new aws instance

```
sudo snap install microk8s --classic --channel=latest/stable
microk8s start
microk8s enable dns ingress metrics-server rbac hostpath-storage
``` 

```
velero install \
  --provider velero.io/aws \
  --bucket bucketname \
  --plugins velero/velero-plugin-for-aws:v1.4.0 \
  --backup-location-config region=eu-central-1 \
  --use-volume-snapshots=false \
  --use-restic \
  --backup-location-config \
      s3Url=https://miniominio,region=miniominio \
  --secret-file ./cloudcreds
```

```
kubectl -n velero patch daemonset.apps/restic --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/volumes/0/hostPath/path", "value":"/var/snap/microk8s/common/var/lib/kubelet/pods"}]' 
```

`velero restore create --from-backup fullbackup`

## Current and expected result

I would expect that the PostgreSQL database is restored. It is not (it is empty)

**Comment by JustinGuese** [comment]
I tried it without the "use-volume-snapshots" flag exactly like in the tutorial, but it does not work

```
velero install \
--use-restic \
--provider velero.io/aws \
--plugins velero/velero-plugin-for-aws:v1.4.0 \
--bucket bucketname \
--secret-file ./cloudcreds \
--backup-location-config region=region,s3ForcePathStyle="true",s3Url=https://s3url,region=region \
--snapshot-location-config region=region
```

**Comment by carkod** [comment]
You may have better luck posting the question at https://discuss.kubernetes.io/t/backup-a-cluster-with-velero/19034.

This is the repo of the microk8s.io website, the documentation is pulled from the kubernetes discourse.

**Comment by JustinGuese** [comment]
yeah just fyi the documentation is wrong/not working anymore

**Comment by ktsakalozos** [comment]
Thank you for reporting this @JustinGuese . We will revise the docs as soon as possible.
