### ISSUE TITLE
Namespace typo in velaro documentation.

### ISSUE THREAD

**Issue by r2DoesInc** [canonical/microk8s.io#556]
## Summary

Minor type in verlaro docs.

`sudo microk8s kubectl create namesnapce workloads`

should be 

`sudo microk8s kubectl create namespace workloads`

## Process

- Follow instructions on https://microk8s.io/docs/velero up to `Create a demo workload`
- Copy and paste the provided commands. `sudo microk8s kubectl create namesnapce workloads`

## Current and expected result

Current:
```
Error: must specify one of -f and -k

error: unknown command "namesnapce workloads"
See 'kubectl create -h' for help and examples
```

Expected:
The namespace to be created

**Comment by carkod** [comment]
@evilnick can you take a look?

**Comment by ktsakalozos** [comment]
Thank you for reporting this @r2DoesInc.

It should be fixed now.
