### ISSUE TITLE
Pods fail when using a different network interface

### ISSUE THREAD

**Issue by raul-ortega** [canonical/microk8s.io#558]
## Summary

- Two nodes, one of then acting as controller and worker, and the other one acting only as worker.
- Both nodes are identical physically, and both are equiped with two network cards (1Gbits and 10 Gbits)
- Initially I installed microk8s using the 1Gbit network cards.
- Now I'm trying to use the 10Gbits network cards, and everything seems to work, but if I disable the 1Gbit netowrk intefaces on the worker node, the pods can not connect to kube services/pods with clusterIP within range 10.152.183.0/24. Pods are scheduled to both nodes, but those scheduled to the worker fails during creation.
- 1 Gbits interfaces IP are within segment 192.168.0.0/24
- 10 Gbits inetrfaces IP are within segment 192.168.1.0/24

## Error message at pod:

(combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c929c2851f8964bdf26a09c791b7598ca519ddf9c4d24f7935821fa0e862692f": error getting ClusterInformation: Get "https://[10.152.183.1]:443/apis/crd.projectcalico.org/v1/clusterinformations/default": dial tcp 10.152.183.1:443: connect: network is unreachable

**Comment by raul-ortega** [comment]
I edited file /var/snap/microk8s/current/args/kube-apiserver, to set the following:

--advertise-address=192.168.1.1

And I also edited file /var/snap/microk8s/current/args/kubelet, to set:

--node-ip=192.168.1.1

Further more, I also set IP.3 = 192.168.1.1 on files: 

/var/snap/microk8s/current/certs/csr.conf.rendered
/var/snap/microk8s/current/certs/csr.conf

After that I restarted microk8s snap service:

sudo snap restart microk8s

No success!

**Comment by ktsakalozos** [comment]
Hi @raul-ortega,

The connection string you use to join a node to a cluster contains an IP. The joining node will route traffic through the interface that leads to that IP.  This is done in `/var/snap/microk8s/current/args/cni-network/cni.yaml` in the `IP_AUTODETECTION_METHOD`. So try this: set the autodetection method to "can-reach" the IP of the 10Gbps gateway and  `kubectl apply` the cni.yaml manifest. I hope it will get us a step further.

**Comment by raul-ortega** [comment]
Dear @ktsakalozos , this is what file cni.yaml (on master node) contains in section # Auto-detect the BGP IP address

            # Auto-detect the BGP IP address.
            - name: IP
              value: "autodetect"
            - name: IP_AUTODETECTION_METHOD
              value: "can-reach=192.168.1.2"

And this is is on the worker node:

           # Auto-detect the BGP IP address.
            - name: IP
              value: "autodetect"
            - name: IP_AUTODETECTION_METHOD
              value: "first-found"

Master node IP of the 10Gbits network interface is 192.168.1.1.

No gateway is used, both 10Gbs network cards are connected through a cross-over cable.

**Comment by raul-ortega** [comment]
Solved:

- In /var/snap/microk8s/current/args/cni-network/cni.yaml on master node set value: "can-reach=192.168.1.1"
- On worker node set the gateway for the network interface to 192.168.1.1

**Comment by raul-ortega** [comment]
Solved, In adition to  @ktsakalozos workarround. I added "gateway: 192.168.1.1" clause to network interface configuration of network card on workder node.

Thanks so much.
