### ISSUE TITLE
The link `Systems using ZFS` under `Alternative install methods for MicroK8s` don't work

### ISSUE THREAD

**Issue by FirelightFlagboy** [canonical/microk8s.io#563]
## Summary

The link `Systems using ZFS` under `Alternative install methods for MicroK8s` link to nothing.

## Process

Go to <https://microk8s.io/docs/install-alternatives#other-environments-4>

## Current and expected result

When I use the inspect tool of my browser on the node element, I see that the `anchor` is missing the `href` attribute.

```html
<li><a>Systems using ZFS</a></li>
```

So I would expected that there is the attribute `href` to be set for this anchor.

## Screenshot

![image](https://user-images.githubusercontent.com/30697622/201480936-8a42224f-604a-4d53-9705-518e064c8502.png)

**Comment by evilnick** [comment]
:+1:

**Comment by evilnick** [comment]
This is actually fixed but I don't have permissions to close the issue :(

**Comment by FirelightFlagboy** [comment]
This link in the [general discussion](https://discuss.kubernetes.io/t/alternative-install-methods-for-microk8s/11257) and on the [website](https://microk8s.io/docs/install-alternatives#other-environments-4) :+1:
