### ISSUE TITLE
imagepullbackoff error with Microk8s helm3

### ISSUE THREAD

**Issue by Naresh-IT-Acheron** [canonical/microk8s.io#585]
## Summary

imagepullbackoff error with Microk8s helm3 
private repository using a secret in the values.yaml, 
where the same images we are able to pull from the repository using docker pull commands 
we have tested it in multiple microk8s clusters with the same repo, and multiple repos and images. the issue is stable.

## Process

microk8s helm3 install

## Current and expected result

the image should be pulled from the repository / use an available image. - None of them are not working.

## Screenshot

NA

## Browser details

NA

**Comment by evilnick** [comment]
This repository is for the microK8s.io website. If you are still experiencing an issue with microK8s, please file an issue in the 
[microk8s repository](https://github.com/canonical/microk8s)
