### ISSUE TITLE
snap refresh microk8s does not upgrade addons after destroying the cluster with microk8s reset

### ISSUE THREAD

**Issue by j-jeurissen** [canonical/microk8s.io#593]
## Summary
snap refresh microk8s does not update the addons.

## Process
destroy cluster:
microk8s leave on all nodes
microk8s reset --destroy-storage on all nodes
sudo snap refresh microk8s --channel 1.26/stable

recreated the cluster:
add node
join
enabled addons
## Current and expected result

metallb tries to pull an old , no longer existing image metallb/controller:v0.9.3

I expected it to pull v0.13.3 as specified on git https://github.com/canonical/microk8s-core-addons/blob/1.26/addons/metallb/metallb.yaml

## Screenshot

[If relevant, include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by evilnick** [comment]
This repository is for the microK8s.io website. If you are still experiencing an issue with microK8s, please file an issue in the 
[microk8s repository](https://github.com/canonical/microk8s)
