### ISSUE TITLE
Typo in  https://microk8s.io/contact-us

### ISSUE THREAD

**Issue by ktsakalozos** [canonical/microk8s.io#631]
## Summary

There is a typo that we need to fix here: 
https://microk8s.io/contact-us 
"Get help with MicorK8s"

## Process

Go to [[List the steps to replicate the issue.]](https://microk8s.io/contact-us)

## Current and expected result

"Get help with MicorK8s"
Should be:
"Get help with MicroK8s"

**Comment by evilnick** [comment]
If someone wants to edit - https://github.com/canonical/microk8s.io/blob/main/templates/contact-us.html and make a PR I can merge it
