### ISSUE TITLE
Add Qt to version Win10

### ISSUE THREAD

**Issue by ghost** [canonical/microk8s.io#640]
## Summary

[Please describe the issue.]

## Process

[List the steps to replicate the issue.]

## Current and expected result

[Describe what happened and what you expected.

## Screenshot

[If relevant, include a screenshot.]

## Browser details

[Optionally - if you can, copy the report generated by [mybrowser.fyi](https://mybrowser.fyi/) - this might help us debug certain types of issues.]

**Comment by lizzochek** [comment]
Hello, please fill in the issue template and reopen the issue if still relevant
