### ISSUE TITLE
Texto A Voz Offline

### ISSUE THREAD

**Issue by ghost** [canonical/microk8s.io#654]
En proceso

**Comment by Alfilblanco2120** [comment]
Lo hice para hacerlo apk pero decidí hacerlo código fuente con la idea que que la usen las personas que tienen perdida de voz o sufren de algún padecimiento que no les permita hablar.
Espero les sirva de algo. Gracias por su apoyo.

**Comment by lizzochek** [comment]
Hello. Thank you for filing an issue. As far as I understand, you resolved it. If it is still relevant, please reopen the issue with more details
